### ISSUE TITLE
feature request : local community events portal

### ISSUE THREAD

**Issue by otivedani** [jatimdevday/community-management-backend#3]
event" dari berbagai komunitas kebanyakan tersebar di berbagai platform, sehingga mungkin biasanya orang (saya pribadi juga) ketinggalan / tidak tahu event" apa yang ada. 
misalnya ada webinar/meetup yang open tapi karena saya belum join grup itu jadi tidak tahu ada event itu, atau kadang ada event" yang tabrakan. 
jadi mungkin akan lebih baik kalau ada suatu wadah / portal informasi event apa saja yang on-going, khususnya di jatim (atau di luar), mungkin semacam fitur di 'browse event nearby' di meetup, integrated dengan sosmed juga.

**Comment by tegarimansyah** [comment]
Halo @otivedani thank you sudah tertarik untuk untuk mau berkontribusi. Ide nya sangat menarik, apakah sudah ada gambaran bagaimana kita bisa membuat fitur "nearby"?

Ohh iya, kalau boleh tau, adakah tech stack yang biasa kamu gunakan?

**Comment by otivedani** [comment]
sepengetahuan saya, biasanya user menentukan posisi awal dan batas jarak (radius) yang diinginkan, untuk kemudian diquery data event mana saja yang berada di jangkauan berdasarkan inputnya dengan bantuan API maps.
atau mungkin bisa juga event yang dicari berdasarkan minat (dan tema" yang 'mendekati' keminatan) user dan diquery ke data" event.

untuk pendekatan ke 2, menurut saya lebih fleksibel mengingat event kebanyakan dilakukan secara online / tidak terbatas lokasi/jarak, tapi tidak menutup kemungkinan keduanya bisa digunakan.

buat tech stack saya lebih prefer python, tapi untuk flask/django masih coba", dan juga tidak menutup kemungkinan untuk belajar yang lain (sedang tertarik c++ / golang juga)

**Comment by tegarimansyah** [comment]
Halo @otivedani , menarik banget idenya. Boleh di share kah id telegramnya? Nanti dari tim kami akan menghubungi untuk ngobrol lebih lanjut.

**Comment by otivedani** [comment]
siap mas :D, telegramnya [t.me/otivedani](t.me/otivedani) juga
