### ISSUE TITLE
Permintaan untuk berkontribusi

### ISSUE THREAD

**Issue by kuuhaku86** [jatimdevday/community-management-backend#4]
Perkenalkan nama saya Yohan Ardiansyah, salah satu mahasiswa di ITS
Saya berminat untuk berkontribusi dalam project ini karena sejak dulu memang sangatlah ingin berkontribusi di project open source maupun project yang bermanfaat untuk sekitar saya.
Telegram : https://t.me/kuuhaku86

**Comment by tegarimansyah** [comment]
Hi Yohan @kuuhaku86 , terima kasih telah tertarik untuk mau berkontribusi disini. Mungkin ada ide yang mau di share kah tentang bagaimana membuat website yang bisa bermanfaat untuk komunitas di Jawa Timur, pengurus maupun anggota. Issue #3 bisa sebagai contoh untuk memberitaukan idemu kepada kami.

Ohh iya, mungkin boleh di share pernah menggunakan atau terbiasa menggunakan tech stack seperti apa ya?

**Comment by kuuhaku86** [comment]
Untuk ide, mengingat daerah saya yaitu Madiun sama sekali tidak ada komunitas IT, maka saya tertarik apabila di web nya ada sebuah fitur untuk orang yang ingin mendaftarkan wilayahnya di web tersebut. Lalu setelah mendaftarkan maka pihak yang mendaftarkan akan diberi langkah konkrit untuk mendirikan suatu komunitas IT di wilayahnya.

**Comment by kuuhaku86** [comment]
Untuk tech stack sendiri paling banyak menggunakan Laravel/Lumen + MySQL atau NodeJS + MongoDB, pernah juga memakai Flask dan PostgreSQL, sekarang sedang mempelajari Django karena tertarik dari pertemuan JDD yang kemarin

**Comment by tegarimansyah** [comment]
Ahh, ada semacam guidance untuk yang mau membangun sebuah komunitas ya. Menarik sekali, sebelumnya kami juga sudah membahas tentang guidance untuk regenerasi yang juga merupakan sebuah tantangan.

Okay nanti akan ada tim yang mengundang ke grup telegram yaa.

**Comment by kuuhaku86** [comment]
ok mas siap
