### ISSUE TITLE
Permintaan untuk turut serta berkontribusi

### ISSUE THREAD

**Issue by AlifvianM** [jatimdevday/community-management-backend#5]
Assalamualaikum. Perkenalkan saya Alifvian Marco asal Banyuwangi dan saya sedang berkuliah di UNEJ. Saya ingin ikut serta berkontribusi dalam jatimdevday karena saya ingin mengembangkan skill saya lebih lanjut. Terima Kasih

telegram: https://t.me/alifvianmarco

**Comment by tegarimansyah** [comment]
Waalaikumsalam

Hi @AlifvianM , terima kasih telah tertarik untuk mau berkontribusi disini. Mungkin ada ide yang mau di share kah tentang bagaimana membuat website yang bisa bermanfaat untuk komunitas di Jawa Timur, pengurus maupun anggota. Issue #3 bisa sebagai contoh untuk memberitaukan idemu kepada kami.

Ohh iya, mungkin boleh di share pernah menggunakan atau terbiasa menggunakan tech stack seperti apa ya?

**Comment by AlifvianM** [comment]
Untuk ide karena ini mengacu pada website komunitas, mungkin seperti website komunitas/organisasi pada umunya. Didalam website nanti diberikan informasi terkait aktivitas yang akan, sedang, dan sudah dilakukan. Lalu ada agenda aktivitas/proker yang akan dilakukan oleh jatimdev selama sebulan atau setahun. Dan yang pasti ada fitur berlangganan gratis dengan mendaftarkan email agar pengunjung dapat menerima informas secara real time terkait jatimdev.

Untuk tech stack yang saya sering gunakan yaitu untuk front-end hanya html dan css, untuk backendnya saya menggunakan django. Mungkin tambahan untuk ide ya. Mungkin di website nanti ada sebuah halaman yang memungkin kan anggota untuk share ilmu seperti layaknya medium dengan tujuan pengunjung dapat memperoleh suatu sumber referensi tambahan dalam bentuk bahasa indonesia. 

sekian dari saya, Terima Kasih

**Comment by tegarimansyah** [comment]
Ahh intinya untuk berbagi dalam bahasa indonesia ya, baik materi maupun kegiatan. Sebelumnya kami juga ada ide untuk membuat sistem "point" untuk peserta maupun pemateri dan kontributor sehingga memiliki history yang jelas dalam aktivitasnya di komunitas.

Thank you masukannya, nanti dari tim kami akan mengundang ke grup yaa.
