### ISSUE TITLE
Permintaan untuk turut serta berkontribusi

### ISSUE THREAD

**Issue by machineska** [jatimdevday/community-management-backend#6]
Halo, saya Riska Abdullah,
mau usul, kalo struktur style sama platformnya ikut pattern dari "**cookiecutter-django**" bisa gak?? mengingat sudah lengkap dan cukup matang dengan pola cookiecutter-django tersebut. Btw apa harus vote dulu kah untuk perubahan code style seperti ini??

**Comment by tegarimansyah** [comment]
Halo @machineska , django cookiecutter bagus banget dan memang cukup lengkap. Kebetulan tim saat ini (dan mungkin yang baru) tidak semuanya terbiasa dengan django, 3rd party, docker dan beberapa yang lainnya jadi kita butuh perubahan yang bertahap. Jika ada beberapa yang bisa mengarahkan, aku kira sangat bagus untuk upgrading skill semua kontributor.

Tertarik kah untuk aku undang ke grup? Kayanya kita pernah ngobrol di django indonesia atau surabaya.py ya? Kamu @\skaterska kan di telegram?

**Comment by machineska** [comment]
Iya @skaterska, insyaAllah saya siap.
